In [1]:
import string
from collections import Counter
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
# from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import warnings
warnings.filterwarnings('ignore')

In [2]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [3]:
# for bag of words
# let's import neessary packages

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [4]:
# let's load a first document
# reading text file

text = open('National_news.txt' , encoding="utf-8").read()

print(text)

Prime Minister Narendra Modi said there are three COVID vaccines under development within the country.
Indian companies have sought technical details on the trials of Russia’s COVID-19 vaccine from the Russian Direct Investment Fund (RDIF) for possible production in India, an Indian Embassy source in Moscow said.

Separately, in an interview to Russian state media Sputnik, Indian Envoy in Moscow D.B. Venkatesh Varma said, “I had a productive discussion with CEO of RDIF, Mr. Kirill Dmitriev, and we are hopeful of positive outcome.”

Also read: Mass production of vaccine in 2021: Russia

Last Tuesday, Russia became the first country to officially register a coronavirus vaccine and Russian President Vladimir Putin announced that one of his daughters had also been inoculated.

“Indian companies are in touch with RDIF regarding vaccines and have asked for technical details about Phase I and Phase II trials of the vaccine and also for production of vaccines in India for third country exports

In [5]:
# first step it will convert in lower case of all pragraph

Lower_document = text.lower()
print(Lower_document)

prime minister narendra modi said there are three covid vaccines under development within the country.
indian companies have sought technical details on the trials of russia’s covid-19 vaccine from the russian direct investment fund (rdif) for possible production in india, an indian embassy source in moscow said.

separately, in an interview to russian state media sputnik, indian envoy in moscow d.b. venkatesh varma said, “i had a productive discussion with ceo of rdif, mr. kirill dmitriev, and we are hopeful of positive outcome.”

also read: mass production of vaccine in 2021: russia

last tuesday, russia became the first country to officially register a coronavirus vaccine and russian president vladimir putin announced that one of his daughters had also been inoculated.

“indian companies are in touch with rdif regarding vaccines and have asked for technical details about phase i and phase ii trials of the vaccine and also for production of vaccines in india for third country exports

In [6]:
# let's clear the documents by removing spaces and punctuation
cleaned_text = Lower_document.translate(str.maketrans('','', string.punctuation))

In [7]:
cleaned_text

'prime minister narendra modi said there are three covid vaccines under development within the country\nindian companies have sought technical details on the trials of russia’s covid19 vaccine from the russian direct investment fund rdif for possible production in india an indian embassy source in moscow said\n\nseparately in an interview to russian state media sputnik indian envoy in moscow db venkatesh varma said “i had a productive discussion with ceo of rdif mr kirill dmitriev and we are hopeful of positive outcome”\n\nalso read mass production of vaccine in 2021 russia\n\nlast tuesday russia became the first country to officially register a coronavirus vaccine and russian president vladimir putin announced that one of his daughters had also been inoculated\n\n“indian companies are in touch with rdif regarding vaccines and have asked for technical details about phase i and phase ii trials of the vaccine and also for production of vaccines in india for third country exports and prod

In [8]:
# let's splitting text into words

tokenization_words = word_tokenize(cleaned_text, 'english')

In [9]:
tokenization_words
print(len(tokenization_words))

517


In [10]:
# removing word from the tockenization words list
final_words =[]
for word in tokenization_words:
    if word not in stopwords.words('english'):
        final_words.append(word)
        

In [11]:
# Lemmatization from plural to single + Base from of a word 

lemma_word=[]

for word in final_words:
    word= WordNetLemmatizer().lemmatize(word)
    lemma_word.append(word)

In [12]:
lemma_word
print(len(lemma_word))

309


In [13]:
# let's call vectorization method

vectore1 = CountVectorizer()
print(vectore1)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [14]:
# this step will convert text into tokens 
vectore1.fit_transform(lemma_word)
print('Bag of words :',vectore1.get_feature_names())

Bag of words : ['2021', '90', 'adding', 'addressing', 'advance', 'afford', 'affordable', 'ahead', 'already', 'also', 'announced', 'apace', 'article', 'asked', 'availability', 'away', 'bearing', 'became', 'biotech', 'capacity', 'case', 'ceo', 'claim', 'clearance', 'closely', 'collaboration', 'come', 'commit', 'company', 'cooperation', 'coronavirus', 'cost', 'country', 'covid', 'covid19', 'daughter', 'day', 'db', 'dear', 'deliver', 'detail', 'development', 'difficult', 'direct', 'discussion', 'disinformation', 'dissemination', 'dmitriev', 'earlier', 'editor', 'embassy', 'enable', 'envoy', 'export', 'extended', 'fight', 'first', 'fort', 'free', 'fund', 'gathering', 'germany', 'give', 'global', 'go', 'greater', 'happening', 'health', 'hope', 'hopeful', 'however', 'huge', 'hydroxychloroquinone', 'ii', 'including', 'increased', 'independence', 'india', 'indian', 'information', 'inoculated', 'interest', 'interview', 'investment', 'journalism', 'keep', 'keeping', 'kirill', 'large', 'last', 'le

In [15]:
vectore1.vocabulary_

{'prime': 128,
 'minister': 101,
 'narendra': 106,
 'modi': 103,
 'said': 152,
 'three': 175,
 'covid': 33,
 'vaccine': 186,
 'development': 41,
 'within': 195,
 'country': 32,
 'indian': 78,
 'company': 28,
 'sought': 160,
 'technical': 172,
 'detail': 40,
 'trial': 181,
 'russia': 150,
 'covid19': 34,
 'russian': 151,
 'direct': 43,
 'investment': 83,
 'fund': 59,
 'rdif': 141,
 'possible': 125,
 'production': 130,
 'india': 77,
 'embassy': 50,
 'source': 161,
 'moscow': 104,
 'separately': 159,
 'interview': 82,
 'state': 164,
 'medium': 100,
 'sputnik': 162,
 'envoy': 52,
 'db': 37,
 'venkatesh': 188,
 'varma': 187,
 'productive': 131,
 'discussion': 44,
 'ceo': 21,
 'mr': 105,
 'kirill': 87,
 'dmitriev': 47,
 'hopeful': 69,
 'positive': 124,
 'outcome': 116,
 'also': 9,
 'read': 142,
 'mass': 98,
 '2021': 0,
 'last': 89,
 'tuesday': 182,
 'became': 17,
 'first': 56,
 'officially': 112,
 'register': 146,
 'coronavirus': 30,
 'president': 126,
 'vladimir': 190,
 'putin': 136,
 'anno

In [16]:
# let's load another documents 
text1 = open('motivational_speech.txt', encoding="utf-8").read()

print(text1)

Facebook CEO Mark Zuckerberg is a deeply private person and can sometimes come off flat as a dial tone. But at Harvard on Thursday he was charming, thoughtful, emotionally raw, and profoundly introspective. Five years after he ruffled feathers on Wall Street by wearing his customary grayT-shirt and jeans during meetings with prospective Facebook IPO investors, Zuckerberg wore a crisp suit and blue tie and opened his remarks with a wry joke at his own expense.

"You all accomplished something I didn't. If I get through this speech today, it will be the first time I actually finish something at Harvard," quipped Zuckerberg, who famously dropped out of Harvard after launching Facebook in his college dorm room 12 years ago.

Zuckerberg spoke at a podium without a teleprompter, and focused on channeling the entrepreneurial spirit exhibited by his generation, to push for big ideas and big projects, equal economic opportunity for all and a global community.

"The greatest successes come from 

In [17]:
# let's convert all pragraph into lower case

lower = text1.lower()

In [18]:
lower

'facebook ceo mark zuckerberg is a deeply private person and can sometimes come off flat as a dial tone. but at harvard on thursday he was charming, thoughtful, emotionally raw, and profoundly introspective. five years after he ruffled feathers on wall street by wearing his customary grayt-shirt and jeans during meetings with prospective facebook ipo investors, zuckerberg wore a crisp suit and blue tie and opened his remarks with a wry joke at his own expense.\n\n"you all accomplished something i didn\'t. if i get through this speech today, it will be the first time i actually finish something at harvard," quipped zuckerberg, who famously dropped out of harvard after launching facebook in his college dorm room 12 years ago.\n\nzuckerberg spoke at a podium without a teleprompter, and focused on channeling the entrepreneurial spirit exhibited by his generation, to push for big ideas and big projects, equal economic opportunity for all and a global community.\n\n"the greatest successes co

In [19]:
# let's clear the documents by removing spaces and punctuation
text1 = lower.translate(str.maketrans('','', string.punctuation))

In [20]:
tokenize_words = word_tokenize(text1,'english')

print(tokenize_words)

['facebook', 'ceo', 'mark', 'zuckerberg', 'is', 'a', 'deeply', 'private', 'person', 'and', 'can', 'sometimes', 'come', 'off', 'flat', 'as', 'a', 'dial', 'tone', 'but', 'at', 'harvard', 'on', 'thursday', 'he', 'was', 'charming', 'thoughtful', 'emotionally', 'raw', 'and', 'profoundly', 'introspective', 'five', 'years', 'after', 'he', 'ruffled', 'feathers', 'on', 'wall', 'street', 'by', 'wearing', 'his', 'customary', 'graytshirt', 'and', 'jeans', 'during', 'meetings', 'with', 'prospective', 'facebook', 'ipo', 'investors', 'zuckerberg', 'wore', 'a', 'crisp', 'suit', 'and', 'blue', 'tie', 'and', 'opened', 'his', 'remarks', 'with', 'a', 'wry', 'joke', 'at', 'his', 'own', 'expense', 'you', 'all', 'accomplished', 'something', 'i', 'didnt', 'if', 'i', 'get', 'through', 'this', 'speech', 'today', 'it', 'will', 'be', 'the', 'first', 'time', 'i', 'actually', 'finish', 'something', 'at', 'harvard', 'quipped', 'zuckerberg', 'who', 'famously', 'dropped', 'out', 'of', 'harvard', 'after', 'launching', 

In [21]:
# let's remove stopwords and punctuations from above paragraphs

stop_words = stopwords.words('english')
punctu = string.punctuation

In [22]:
# let's take  empty_list to store data

cleaned_text =[]

for word in tokenize_words:
    if word not in punctu:
        if word not in stop_words:
            cleaned_text.append(word)
print("cleaned_text >--", len(cleaned_text))
print('\n',cleaned_text)

cleaned_text >-- 479

 ['facebook', 'ceo', 'mark', 'zuckerberg', 'deeply', 'private', 'person', 'sometimes', 'come', 'flat', 'dial', 'tone', 'harvard', 'thursday', 'charming', 'thoughtful', 'emotionally', 'raw', 'profoundly', 'introspective', 'five', 'years', 'ruffled', 'feathers', 'wall', 'street', 'wearing', 'customary', 'graytshirt', 'jeans', 'meetings', 'prospective', 'facebook', 'ipo', 'investors', 'zuckerberg', 'wore', 'crisp', 'suit', 'blue', 'tie', 'opened', 'remarks', 'wry', 'joke', 'expense', 'accomplished', 'something', 'didnt', 'get', 'speech', 'today', 'first', 'time', 'actually', 'finish', 'something', 'harvard', 'quipped', 'zuckerberg', 'famously', 'dropped', 'harvard', 'launching', 'facebook', 'college', 'dorm', 'room', '12', 'years', 'ago', 'zuckerberg', 'spoke', 'podium', 'without', 'teleprompter', 'focused', 'channeling', 'entrepreneurial', 'spirit', 'exhibited', 'generation', 'push', 'big', 'ideas', 'big', 'projects', 'equal', 'economic', 'opportunity', 'global', 'c

In [29]:
lemma_word1=[]

for word in cleaned_text:
    word= WordNetLemmatizer().lemmatize(word)
    lemma_word1.append(word)

In [30]:
lemma_word1

['facebook',
 'ceo',
 'mark',
 'zuckerberg',
 'deeply',
 'private',
 'person',
 'sometimes',
 'come',
 'flat',
 'dial',
 'tone',
 'harvard',
 'thursday',
 'charming',
 'thoughtful',
 'emotionally',
 'raw',
 'profoundly',
 'introspective',
 'five',
 'year',
 'ruffled',
 'feather',
 'wall',
 'street',
 'wearing',
 'customary',
 'graytshirt',
 'jean',
 'meeting',
 'prospective',
 'facebook',
 'ipo',
 'investor',
 'zuckerberg',
 'wore',
 'crisp',
 'suit',
 'blue',
 'tie',
 'opened',
 'remark',
 'wry',
 'joke',
 'expense',
 'accomplished',
 'something',
 'didnt',
 'get',
 'speech',
 'today',
 'first',
 'time',
 'actually',
 'finish',
 'something',
 'harvard',
 'quipped',
 'zuckerberg',
 'famously',
 'dropped',
 'harvard',
 'launching',
 'facebook',
 'college',
 'dorm',
 'room',
 '12',
 'year',
 'ago',
 'zuckerberg',
 'spoke',
 'podium',
 'without',
 'teleprompter',
 'focused',
 'channeling',
 'entrepreneurial',
 'spirit',
 'exhibited',
 'generation',
 'push',
 'big',
 'idea',
 'big',
 'proj

In [25]:
# let's call vectorization method

vector = CountVectorizer()
print(vector)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [32]:
# this step will convert text into tokens 
vector.fit_transform(lemma_word1)
print('Bag of words :',vector.get_feature_names())

Bag of words : ['10', '12', '33', '623', 'accomplished', 'acknowledged', 'actually', 'ad', 'address', 'afford', 'afforded', 'ago', 'allows', 'alone', 'along', 'also', 'appeal', 'applause', 'asked', 'attend', 'audience', 'away', 'back', 'bathroom', 'belltower', 'best', 'beyoncé', 'big', 'billion', 'billionaire', 'birthday', 'blown', 'blue', 'board', 'book', 'breakfast', 'bring', 'broke', 'built', 'business', 'call', 'came', 'cant', 'ceo', 'challenge', 'channeling', 'charming', 'chat', 'child', 'close', 'code', 'college', 'come', 'commencement', 'community', 'continues', 'conversation', 'could', 'country', 'create', 'crisp', 'culture', 'customary', 'cynical', 'date', 'daughter', 'day', 'deeply', 'dentist', 'deny', 'deportation', 'dial', 'didnt', 'doesnt', 'dollar', 'dont', 'dorm', 'dormitory', 'dream', 'dropped', 'easy', 'economic', 'eliciting', 'emotionally', 'end', 'enough', 'enterprise', 'entrepreneurial', 'equal', 'even', 'every', 'everyone', 'exhibited', 'expecting', 'expense', 'exp

In [33]:
vector.vocabulary_

{'facebook': 98,
 'ceo': 43,
 'mark': 184,
 'zuckerberg': 333,
 'deeply': 67,
 'private': 226,
 'person': 217,
 'sometimes': 265,
 'come': 52,
 'flat': 114,
 'dial': 71,
 'tone': 300,
 'harvard': 140,
 'thursday': 295,
 'charming': 46,
 'thoughtful': 291,
 'emotionally': 83,
 'raw': 236,
 'profoundly': 227,
 'introspective': 156,
 'five': 113,
 'year': 329,
 'ruffled': 252,
 'feather': 105,
 'wall': 310,
 'street': 274,
 'wearing': 315,
 'customary': 62,
 'graytshirt': 133,
 'jean': 159,
 'meeting': 187,
 'prospective': 229,
 'ipo': 158,
 'investor': 157,
 'wore': 321,
 'crisp': 60,
 'suit': 280,
 'blue': 32,
 'tie': 296,
 'opened': 206,
 'remark': 240,
 'wry': 328,
 'joke': 162,
 'expense': 94,
 'accomplished': 4,
 'something': 264,
 'didnt': 72,
 'get': 123,
 'speech': 269,
 'today': 298,
 'first': 112,
 'time': 297,
 'actually': 6,
 'finish': 111,
 'quipped': 235,
 'famously': 102,
 'dropped': 79,
 'launching': 170,
 'college': 51,
 'dorm': 76,
 'room': 249,
 '12': 1,
 'ago': 11,
 '

In [31]:
# let's check wether word  present or not
vector.fit(lemma_word)
new_word = vector.transform(lemma_word1)
print('text peresent at :',new_word.toarray())

# let's compare with original indexes 

print('original indexes',vectore1.get_feature_names())


text peresent at : [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
original indexes ['2021', '90', 'adding', 'addressing', 'advance', 'afford', 'affordable', 'ahead', 'already', 'also', 'announced', 'apace', 'article', 'asked', 'availability', 'away', 'bearing', 'became', 'biotech', 'capacity', 'case', 'ceo', 'claim', 'clearance', 'closely', 'collaboration', 'come', 'commit', 'company', 'cooperation', 'coronavirus', 'cost', 'country', 'covid', 'covid19', 'daughter', 'day', 'db', 'dear', 'deliver', 'detail', 'development', 'difficult', 'direct', 'discussion', 'disinformation', 'dissemination', 'dmitriev', 'earlier', 'editor', 'embassy', 'enable', 'envoy', 'export', 'extended', 'fight', 'first', 'fort', 'free', 'fund', 'gathering', 'germany', 'give', 'global', 'go', 'greater', 'happening', 'health', 'hope', 'hopeful', 'however', 'huge', 'hydroxychloroquinone', 'ii', 'including', 'increased', 'independence', 'india', 

In [46]:
common_word = []

for i in vectore1.get_feature_names():
    for j in vector.get_feature_names():
        if i == j:
            common_word.append(i)


In [47]:
common_word

['afford',
 'also',
 'asked',
 'away',
 'ceo',
 'come',
 'country',
 'daughter',
 'day',
 'first',
 'global',
 'go',
 'greater',
 'keep',
 'need',
 'one',
 'opportunity',
 'quickly',
 'said',
 'start',
 'three',
 'time',
 'told',
 'use',
 'world']